config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=>'',
  					 :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
  					 :controllers=>{:registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  resources :users, only: [:show]
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/, :show => '786>x447'
  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos


  validates :home_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 75}
  validates :summary, presence: true, length: {maximum: 600}
  validates :address, presence: true
  validates :price, numericality: {only_integer: true, greater_than: 5}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :fullname, presence:true, length: {maximum:50}

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assers/default_image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :rooms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  protected
  def update_resource(resource, params)
    
      resource.update_without_password(params)
    end
  
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

before_action :set_room, only: [:show, :edit, :update] 
before_action :authenticate_user!, except: [:show]
before_action :require_same_user, only: [:edit, :update]


	def index
      @rooms = current_user.rooms 
   end

   def new
      @room = current_user.rooms.build
   end

   def create
      @room = current_user.rooms.build(room_params) 
      if @room.save
          if params[:images]
              params[:images].each do |i|
                  @room.photos.create(image: i)
              end
          end
          @photos = @room.photos

          redirect_to edit_room_path(@room), notice:"Your Ad has benn successfully added"
      else
          render :new
      end
   end

   def show
       @photos = @room.photos

   end

   def edit
       @photos = @room.photos

   end

   def update
        if @room.update(room_params)
            if params[:images]
              params[:images].each do |i|
                  @room.photos.create(image: i)
              end
            end
            @photos = @room.photos
            redirect_to edit_room_path(@room), notice:"Modification registred..."
        else
           render :edit
        end
   end

private
    def set_room
        @room = Room.find(params[:id]) 
    end

    def room_params
       params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room,
       :listing_name, :summary, :address, :is_wifi,:is_pet, :is_tv, :is_closet,
       :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, :active) 
    end

    def require_same_user
       if current_user.id != @room.user_id
           flash[:danger] = "You dont have the rights to edit this page"
           redirect_to root_path
       end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id]) 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		user.avatar.url
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'HomExchange', root_path, {:class=>"navbar-brand"}%>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
               <%= link_to new_room_path do %>
                 <i class="fa fa-home fa-lg"></i>Become a host
               <% end %>
             </li>

        <% if (!user_signed_in?) %>  
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% else %>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user), class:"image-circle avatar-small" %><%= current_user.fullname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Mes Voyage', root_path %></li>
                <li><%= link_to 'Edit My Profil', edit_user_registration_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to 'Log Out',  destroy_user_session_path, method: :delete %></li>

              </ul>
            </li>

        <% end %>

          </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppExchange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

  	<%= render 'layouts/navigation' %>

    <%= render 'shared/message' %>



    <div class ="container">
    <%= yield %></div>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Bienvenue</h2>

<%= link_to 'Sign Up', new_user_registration_path %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Log Out',  destroy_user_session_path, method: :delete %>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
    	Become a host
    </div>
    <div class="panel-body">
        <div class="container">

            <%= form_for @room do |f| %>
                <%= render 'shared/errors' %>

	            <div class="row">

	                <div class="col-md-4 select">
	                    <div class="form-group">
	                        <label>Type of dwelling</label>
	                        <%= f.select :home_type, [["House","House"],["Apartment", "Apartment"],
	                        ["Bed & Breakfast", "Bed & breakfast"]], id: "home_type", prompt:"Select your home type...",
	                        class:"form-control" %>
	                     </div>                         
	                 </div>

	                <div class="col-md-4 select">
	                    <div class="form-group">
	                        <label>Housing type</label>
	                        <%= f.select :room_type, [["Entire homer","Entire home"],["Private Room", "Private Room"],
	                        ["Shared room", "Shared room"]], prompt:"select your choice...",
	                        class:"form-control" %>
	                    </div>
	                </div>

	                <div class="col-md-4 select">
	                    <div class="form-group">
	                        <label>How many travelers?</label>
	                        <%= f.select :accomodate, [["1 traveler",1],["2 travelers",2],
	                        ["3 travelers",3], ["4 travelers",4] ,["5 travelers",5],
	                        ["6 voyageurs",6]], prompt:"Select a number of travelers...",
	                        class:"form-control" %>
	                    </div>
	                </div>
	            </div>

	            <div class="row">
	                    <div class="col-md-4 select">
	                        <div class="form-group">
	                            <label>Rooms</label>
	                            <%= f.select :bed_room, [["1",1],["2",2],
	                            ["3",3], ["4",4]], prompt:"Select a number of rooms",
	                            class:"form-control" %>
	                        </div>
	                    </div>
	                    <div class="col-md-4 select">
	                        <div class="form-group">
	                            <label>Bath_room</label>
	                            <%= f.select :bath_room, [["1",1],["2",2],
	                            ["3",3], ["4",4]], prompt:"Select a numbr of bathrooms",
	                            class:"form-control" %>
	                        </div>
	                    </div>
	                    
	            </div>

	            <div class="row">
	                <div class="form-group">
	                    <label>Give your home a name</label>
	                    <%= f.text_field :listing_name, placeholder:"Ad title", class:"form-control" %>
	                </div>
	            </div>
	            
	            <div class="row">
	                <div class="form-group">
	                    <label>Summary</label>
	                    <%= f.text_area :summary, placeholder:"Describe the decor, the atmosphere, what is nearby, your pet(if you have one), etc ...", class:"form-control" %>
	                </div>
	            </div>
	            
	            <div class="row">
	                <div class="form-group">
	                    <label>Adress</label>
	                    <%= f.text_field :address, placeholder:"Where is your home located?", class:"form-control" %>
	                </div>
	            </div>

	            <div class="row">
	                <div class="col-md-4">
	                    <div class="form-group">
	                        <%= f.check_box :is_wifi %>Wifi
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_tv %>TV
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_closet %>Wardrobe / Dresser
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_pet %>Pet
	                    </div>
	                </div>
	                <div class="col-md-4">
	                    <div class="form-group">
	                        <%= f.check_box :is_kitchen %>Kitchen
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_breakfast %>Breakfast, coffee, tea
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_heating %>Heater
	                    </div>
	                    <div class="form-group">
	                        <%= f.check_box :is_air %>Air conditioner
	                    </div>
	                </div>
	            </div>

	            <div class="row">
	                <div class="col-md-4">
	                    <div class="form-group">
	                        <label>Price per night</label>
	                        <div class="input-group">
	                            <%= f.text_field :price, placeholder:"ex: 45€", class: "form-control" %>
	                        <div class="input-group-addon">€</div>
	                        </div>
	                    </div>
	                </div>
	            </div>

	            <div class="row">
	                <div class="form-group">
	                    <%= f.check_box :active %> Ad active
	                </div>
	            </div>

	            <div class="actions">
                    <%= f.submit "I validate my ad", class:"btn btn-primary" %>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/update.html.erb
<%= render 'form' %>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>

<% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>
    <script type="text/javascript">
        <% @room.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>

<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice','info') %>
        toastr['<%= type %>']('<%= f[1] %>')
        <% end %>
    </script>


<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<%= image_tag avatar_url(@user), class:"avatar-full"%>
		<div class="panel panel-default">
           <div class="panel-heading">Vérification</div>
           <div class="panel-body">
               Email: <%= @user.email %><br>
               Phone: <%= @user.phone_number %><br>
           </div>
       </div>
	</div>
	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>
		<div class="description row-space-3">
            <%= @user.description %>
        </div>
	</div>
</div>